### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by freecsdn** [android-cjj/Android-MaterialRefreshLayout#10]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.cjj.f.setProgressValue(int)' on a null object reference
	at com.cjj.MaterialRefreshLayout.setProgressValue(MaterialRefreshLayout.java:393)
	at com.cjj.MaterialRefreshLayout.g(MaterialRefreshLayout.java:484)

**Comment by esteedqueen** [comment]
I'm also having this problem... Did you resolve yours @freecsdn ?

**Comment by plevavas** [comment]
+1

**Comment by TechnoTrancer** [comment]
I have the same issue in my case i use a ViewPager and is caused by turning off screen phone
when turn on again, the animation was stopped.
So when i want to finishRefresh(); it attemps to invoke a method on null object.

Using android.support.v4.widget.SwipeRefreshLayout the animation persist after a lock/unlock process.

**Comment by jiang111** [comment]
+1

**Comment by alinekborges** [comment]
+1

**Comment by wkh9728** [comment]
+1
