### ISSUE TITLE
头部有时候会报这NullPointException

### ISSUE THREAD

**Issue by luenghw** [android-cjj/Android-MaterialRefreshLayout#44]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.cjj.CircleProgressBar.setProgress(int)' on a null object reference
	at com.cjj.MaterialHeadView$1.run(MaterialHeadView.java:96)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by colincachia** [comment]
Same issue, replicable on Android API 22

**Comment by therealccarter** [comment]
Anyone figured this out? If I can't find a way around this, I'll have to find another library.
