### ISSUE TITLE
最近经常崩溃

### ISSUE THREAD

**Issue by baoxiehao** [android-cjj/Android-MaterialRefreshLayout#63]
materialrefeshlayout 01-28 13:29:08.066 E/AndroidRuntime(27005): FATAL EXCEPTION: main
01-28 13:29:08.066 E/AndroidRuntime(27005): Process: com.yekong.droid.simpleapp, PID: 27005
01-28 13:29:08.066 E/AndroidRuntime(27005): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.cjj.CircleProgressBar.setProgress(int)' on a null object reference
01-28 13:29:08.066 E/AndroidRuntime(27005): 	at com.cjj.MaterialHeadView$1.run(MaterialHeadView.java:96)
01-28 13:29:08.066 E/AndroidRuntime(27005): 	at android.os.Handler.handleCallback(Handler.java:742)
01-28 13:29:08.066 E/AndroidRuntime(27005): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-28 13:29:08.066 E/AndroidRuntime(27005): 	at android.os.Looper.loop(Looper.java:154)
01-28 13:29:08.066 E/AndroidRuntime(27005): 	at android.app.ActivityThread.main(ActivityThread.java:5514)
01-28 13:29:08.066 E/AndroidRuntime(27005): 	at java.lang.reflect.Method.invoke(Native Method)
01-28 13:29:08.066 E/AndroidRuntime(27005): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:736)
01-28 13:29:08.066 E/AndroidRuntime(27005): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)

没有特别调用接口，就是调用了 setMaterialRefreshListener

**Comment by marcoaros** [comment]
# main(1)
java.lang.NullPointerException
1 com.cjj.e$1.run(MaterialHeadView.java:96)
2 android.os.Handler.handleCallback(Handler.java:733)
3 android.os.Handler.dispatchMessage(Handler.java:95)
I also have this problem, but I check the latest code has this judge
                if (circleProgressBar != null) {
                    circleProgressBar.setProgress(progressValue);
                }
but I have used the latest version, the code just like this:
circleProgressBar.setProgress(progressValue);

please publish the latest version, thanks a lot
