### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by abhin-dexlock** [android-cjj/Android-MaterialRefreshLayout#74]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.cjj.CircleProgressBar.setProgress(int)' on a null object reference
                      at com.cjj.MaterialHeadView$1.run(MaterialHeadView.java:96)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:9

**Comment by prashant31191** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: ca.chiropractic, PID: 21620
                                                                 java.lang.NullPointerException
                                                                     at com.cjj.MaterialHeadView$1.run(MaterialHeadView.java:96)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:146)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5598)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                     at dalvik.system.NativeStart.main(Native Method)
