### ISSUE TITLE
MaterialRefreshLayout

### ISSUE THREAD

**Issue by freecsdn** [android-cjj/Android-MaterialRefreshLayout#9]
java.lang.NullPointerException
	at com.cjj.g.run(MaterialHeadView.java:96)
	at android.os.Handler.handleCallback(Handler.java:800)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5469)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:857)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by colincachia** [comment]
Did anyone figure out how to go around this issue?
